import { MastermindZkApp } from './Mastermind.js';
import {
  StepProgram,
  StepProgramProof,
  AuthInputs,
  PublicOutputs,
} from './stepProgram.js';
import {
  separateCombinationDigits,
  compressCombinationDigits,
  validateCombination,
  serializeClue,
  deserializeClue,
  serializeClueHistory,
  deserializeClueHistory,
  getClueFromGuess,
  checkIfSolved,
  compressTurnCountMaxAttemptSolved,
  separateTurnCountAndMaxAttemptSolved,
  compressRewardAndFinalizeSlot,
  separateRewardAndFinalizeSlot,
  serializeCombinationHistory,
  deserializeCombinationHistory,
  updateElementAtIndex,
  getElementAtIndex,
} from './utils.js';

export {
  MastermindZkApp,
  StepProgram,
  AuthInputs,
  PublicOutputs,
  StepProgramProof,
  separateCombinationDigits,
  compressCombinationDigits,
  validateCombination,
  serializeClue,
  deserializeClue,
  serializeClueHistory,
  deserializeClueHistory,
  getClueFromGuess,
  checkIfSolved,
  compressTurnCountMaxAttemptSolved,
  separateTurnCountAndMaxAttemptSolved,
  compressRewardAndFinalizeSlot,
  separateRewardAndFinalizeSlot,
  serializeCombinationHistory,
  deserializeCombinationHistory,
  updateElementAtIndex,
  getElementAtIndex,
};
